import { Game } from "./types";

export const GAME_LIBRARY: Game[] = [
  {
    id: "zelda-botw",
    title: "塞尔达传说：旷野之息",
    platform: "Switch",
    year: 2017,
  },
  {
    id: "mario-odyssey",
    title: "超级马里奥：奥德赛",
    platform: "Switch",
    year: 2017,
  },
  {
    id: "witcher-3",
    title: "巫师3：狂猎",
    platform: "PC",
    year: 2015,
  },
  {
    id: "elden-ring",
    title: "艾尔登法环",
    platform: "PC",
    year: 2022,
  },
  {
    id: "hades",
    title: "黑帝斯",
    platform: "PC",
    year: 2020,
  },
  {
    id: "hollow-knight",
    title: "空洞骑士",
    platform: "PC",
    year: 2017,
  },
  {
    id: "celeste",
    title: "蔚蓝",
    platform: "PC",
    year: 2018,
  },
  {
    id: "rdr2",
    title: "荒野大镖客2",
    platform: "PS4",
    year: 2018,
  },
  {
    id: "persona5",
    title: "女神异闻录5",
    platform: "PS4",
    year: 2016,
  },
  {
    id: "minecraft",
    title: "我的世界",
    platform: "Multi",
    year: 2011,
  },
  // 扩充部分
  {
    id: "god-of-war-2018",
    title: "战神",
    platform: "PS4",
    year: 2018,
  },
  {
    id: "final-fantasy-7-remake",
    title: "最终幻想7：重制版",
    platform: "PS4",
    year: 2020,
  },
  {
    id: "cyberpunk-2077",
    title: "赛博朋克2077",
    platform: "PC",
    year: 2020,
  },
  {
    id: "monster-hunter-world",
    title: "怪物猎人：世界",
    platform: "Multi",
    year: 2018,
  },
  {
    id: "overwatch",
    title: "守望先锋",
    platform: "Multi",
    year: 2016,
  },
  {
    id: "apex-legends",
    title: "Apex英雄",
    platform: "Multi",
    year: 2019,
  },
  {
    id: "doom-eternal",
    title: "毁灭战士：永恒",
    platform: "PC",
    year: 2020,
  },
  {
    id: "stardew-valley",
    title: "星露谷物语",
    platform: "Multi",
    year: 2016,
  },
  {
    id: "animal-crossing-nh",
    title: "集合啦！动物森友会",
    platform: "Switch",
    year: 2020,
  },
  {
    id: "gta5",
    title: "侠盗猎车手5",
    platform: "Multi",
    year: 2013,
  },
  {
    id: "splatoon-3",
    title: "斯普拉遁3",
    platform: "Switch",
    year: 2022,
  },
  {
    id: "bloodborne",
    title: "血源诅咒",
    platform: "PS4",
    year: 2015,
  },
  {
    id: "dark-souls-3",
    title: "黑暗之魂3",
    platform: "Multi",
    year: 2016,
  },
  {
    id: "league-of-legends",
    title: "英雄联盟",
    platform: "PC",
    year: 2009,
  },
  {
    id: "genshin-impact",
    title: "原神",
    platform: "Multi",
    year: 2020,
  },
  {
    id: "metroid-dread",
    title: "密特罗德 生存恐惧",
    platform: "Switch",
    year: 2021,
  },
  {
    id: "bayonetta-3",
    title: "猎天使魔女3",
    platform: "Switch",
    year: 2022,
  },
  {
    id: "sekiro",
    title: "只狼：影逝二度",
    platform: "Multi",
    year: 2019,
  },
  {
    id: "death-stranding",
    title: "死亡搁浅",
    platform: "Multi",
    year: 2019,
  },
  {
    id: "nier-automata",
    title: "尼尔：机械纪元",
    platform: "Multi",
    year: 2017,
  },
  {
    id: "portal-2",
    title: "传送门2",
    platform: "PC",
    year: 2011,
  },
  {
    id: "left-4-dead-2",
    title: "求生之路2",
    platform: "PC",
    year: 2009,
  },
  {
    id: "valheim",
    title: "英灵神殿",
    platform: "PC",
    year: 2021,
  },
  {
    id: "terraria",
    title: "泰拉瑞亚",
    platform: "Multi",
    year: 2011,
  },
  {
    id: "dota2",
    title: "刀塔2",
    platform: "PC",
    year: 2013,
  },
  {
    id: "counter-strike-go",
    title: "反恐精英：全球攻势",
    platform: "PC",
    year: 2012,
  },
  {
    id: "halo-infinite",
    title: "光环：无限",
    platform: "Multi",
    year: 2021,
  },
  {
    id: "forza-horizon-5",
    title: "极限竞速：地平线5",
    platform: "Multi",
    year: 2021,
  },
  {
    id: "pokemon-sv",
    title: "宝可梦 朱/紫",
    platform: "Switch",
    year: 2022,
  },
  {
    id: "super-smash-bros-ultimate",
    title: "任天堂明星大乱斗 特别版",
    platform: "Switch",
    year: 2018,
  },
  {
    id: "super-mario-kart-8",
    title: "马里奥赛车8 豪华版",
    platform: "Switch",
    year: 2017,
  },
  {
    id: "kirby-forgotten-land",
    title: "星之卡比 探索发现",
    platform: "Switch",
    year: 2022,
  },
  {
    id: "fire-emblem-three-houses",
    title: "火焰纹章 风花雪月",
    platform: "Switch",
    year: 2019,
  },
  {
    id: "xenoblade-chronicles-3",
    title: "异度神剑3",
    platform: "Switch",
    year: 2022,
  },
  {
    id: "splatoon-2",
    title: "斯普拉遁2",
    platform: "Switch",
    year: 2017,
  },
  {
    id: "super-mario-3d-world",
    title: "超级马里奥3D世界 + 狂怒世界",
    platform: "Switch",
    year: 2021,
  },
  {
    id: "metroid-prime-remastered",
    title: "密特罗德Prime 重制版",
    platform: "Switch",
    year: 2023,
  },
  {
    id: "smash-bros-brawl",
    title: "任天堂明星大乱斗X",
    platform: "Wii",
    year: 2008,
  },
  {
    id: "ocarina-of-time",
    title: "塞尔达传说：时之笛",
    platform: "N64",
    year: 1998,
  },
  {
    id: "majora-mask",
    title: "塞尔达传说：穆修拉的假面",
    platform: "N64",
    year: 2000,
  },
  {
    id: "bioshock-infinite",
    title: "生化奇兵：无限",
    platform: "Multi",
    year: 2013,
  },
  {
    id: "bioshock",
    title: "生化奇兵",
    platform: "Multi",
    year: 2007,
  },
  {
    id: "mass-effect-2",
    title: "质量效应2",
    platform: "Multi",
    year: 2010,
  },
  {
    id: "mass-effect-legendary",
    title: "质量效应 传奇版",
    platform: "Multi",
    year: 2021,
  },
  {
    id: "battlefield-1",
    title: "战地1",
    platform: "Multi",
    year: 2016,
  },
  {
    id: "battlefield-2042",
    title: "战地2042",
    platform: "Multi",
    year: 2021,
  },
  {
    id: "call-of-duty-modern-warfare",
    title: "使命召唤：现代战争",
    platform: "Multi",
    year: 2019,
  },
  {
    id: "call-of-duty-warzone",
    title: "使命召唤：战区",
    platform: "Multi",
    year: 2020,
  },
  {
    id: "call-of-duty-black-ops-2",
    title: "使命召唤：黑色行动2",
    platform: "Multi",
    year: 2012,
  },
  {
    id: "resident-evil-2-remake",
    title: "生化危机2 重制版",
    platform: "Multi",
    year: 2019,
  },
  {
    id: "resident-evil-4-remake",
    title: "生化危机4 重制版",
    platform: "Multi",
    year: 2023,
  },
  {
    id: "resident-evil-village",
    title: "生化危机8 村庄",
    platform: "Multi",
    year: 2021,
  },
  {
    id: "street-fighter-6",
    title: "街头霸王6",
    platform: "Multi",
    year: 2023,
  },
  {
    id: "tekken-7",
    title: "铁拳7",
    platform: "Multi",
    year: 2015,
  },
  {
    id: "mortal-kombat-11",
    title: "真人快打11",
    platform: "Multi",
    year: 2019,
  },
  {
    id: "dragon-ball-fighterz",
    title: "龙珠斗士Z",
    platform: "Multi",
    year: 2018,
  },
  {
    id: "guilty-gear-strive",
    title: "罪恶装备 奋战",
    platform: "Multi",
    year: 2021,
  },
  {
    id: "nba-2k23",
    title: "NBA 2K23",
    platform: "Multi",
    year: 2022,
  },
  {
    id: "fifa-23",
    title: "FIFA 23",
    platform: "Multi",
    year: 2022,
  },
  {
    id: "madden-nfl-23",
    title: "麦登橄榄球 23",
    platform: "Multi",
    year: 2022,
  },
  {
    id: "the-sims-4",
    title: "模拟人生4",
    platform: "Multi",
    year: 2014,
  },
  {
    id: "simcity-2013",
    title: "模拟城市2013",
    platform: "PC",
    year: 2013,
  },
  {
    id: "civilization-6",
    title: "文明6",
    platform: "Multi",
    year: 2016,
  },
  {
    id: "age-of-empires-4",
    title: "帝国时代4",
    platform: "PC",
    year: 2021,
  },
  {
    id: "starcraft-2",
    title: "星际争霸2",
    platform: "PC",
    year: 2010,
  },
  {
    id: "warcraft-3",
    title: "魔兽争霸3",
    platform: "PC",
    year: 2002,
  },
  {
    id: "diablo-4",
    title: "暗黑破坏神4",
    platform: "Multi",
    year: 2023,
  },
  {
    id: "diablo-3",
    title: "暗黑破坏神3",
    platform: "Multi",
    year: 2012,
  },
  {
    id: "path-of-exile",
    title: "流放之路",
    platform: "Multi",
    year: 2013,
  },
  {
    id: "fortnite",
    title: "堡垒之夜",
    platform: "Multi",
    year: 2017,
  },
  {
    id: "pubg",
    title: "绝地求生",
    platform: "Multi",
    year: 2017,
  },
  {
    id: "tetris-effect",
    title: "俄罗斯方块 效应",
    platform: "Multi",
    year: 2018,
  },
  {
    id: "pac-man",
    title: "吃豆人",
    platform: "Arcade",
    year: 1980,
  },
  {
    id: "sonic-mania",
    title: "索尼克 狂热",
    platform: "Multi",
    year: 2017,
  },
  {
    id: "assassins-creed-valhalla",
    title: "刺客信条：英灵殿",
    platform: "Multi",
    year: 2020,
  },
  {
    id: "assassins-creed-odyssey",
    title: "刺客信条：奥德赛",
    platform: "Multi",
    year: 2018,
  },
  {
    id: "assassins-creed-2",
    title: "刺客信条2",
    platform: "Multi",
    year: 2009,
  },
  {
    id: "ghost-of-tsushima",
    title: "对马岛之魂",
    platform: "PS4",
    year: 2020,
  },
  {
    id: "the-last-of-us-2",
    title: "最后生还者2",
    platform: "PS4",
    year: 2020,
  },
  {
    id: "the-last-of-us-remastered",
    title: "最后生还者 重制版",
    platform: "PS4",
    year: 2014,
  },
];
